# Site settings
title: Nina J. Lu
email: nina@ninalu.me
description: "The personal blog of a former Apple and Microsoft intern."
baseurl: "/"
url: "http://ninalu.github.io"
twitter_username: ninajlu
github_username:  ninajlu
facebook_username:  atomicnum2811

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
